### ISSUE TITLE
Better English translations

### ISSUE THREAD

**Issue by QuantumToasted** [QuantumToasted/Administrator#8]
So far, the English (`en-US`) translations are fine grammatically, but I have some people have suggested giving the bot more personality - to make her more like the Administrator. I do not feel as though the current text does a good enough job of it.

I would love to see this realized, but I don't feel as I could do a good enough job of translating the plain old text into something that sounds like something she would say herself - the right mixture of formality, sass, and sincerity...without going over the top.

Anyone who feels they might be able to accomplish this, or even simply offer small changes here and there to the current translations to give them more personality, is welcome to submit a pull request or suggest changes here.

For reference, the English localization file can be found here: https://github.com/QuantumToasted/Administrator/blob/rewrite/Administrator/Data/Responses/en-US.json

**Comment by thecatitude** [comment]
![image](https://user-images.githubusercontent.com/44521335/54410131-0ac23900-474f-11e9-8b01-cd069dc64587.png)

**Comment by coler-spec** [comment]
Rokaq is excellent at writing things with personality in them. Perhaps you should contact him?

**Comment by xTeramites** [comment]
I would say just maybe add like some sass, possibly a bit of sarcasm.

**Comment by QuantumToasted** [comment]
Closing this for now as the bot has gone in a completely different direction with regard to localization. It's not planned for the foreseeable future, and I'm currently happy with the English language responses, since the bot's personality should not come at the cost of commands being clear and easy to understand.
